### ISSUE TITLE
change CPU#runQueue to be single (per-core) producer

### ISSUE THREAD

**Issue by xedin** [xedin/windmill#2]

**Comment by xedin** [comment]
@nitsanw Just want to get your opinion about this if possible. I've dug deeper into jctools-core and it looks like what I wanted for this is not necessary MpscOnSpscQueue which would have high memory overhead on wide machines but rather MpscComboundQueue which splits MpscArrayQueue into multiple components based on number of CPUs available/given to minimize contention. I've wrote small benchmark to make sure that it behaves better than pure MpscArrayQueue for the contended use-case I had in mind and it certainly does, benchmark is located at https://gist.github.com/xedin/1159b85047f7685c41c8 it does chaining where result of one CPU is mapped in the chain to other CPUs, as well as, multi-dispatch and multi-dispatch in the loop where multiple CPUs will try to schedule work on a single one, here are the numbers:

MpscArrayQueue(1 << 20)
```
MyBenchmark.multiDispatch       1000  thrpt    5  1488776.410 ± 380969.509  ops/s
MyBenchmark.multiDispatch1K     1000  thrpt    5     2683.162 ±    381.184  ops/s
MyBenchmark.taskChaining        1000  thrpt    5  1302255.286 ± 274655.761  ops/s
```

MpscCompoundQueue(1 << 20)
```
Benchmark                    (count)   Mode  Cnt        Score       Error  Units
MyBenchmark.multiDispatch       1000  thrpt    5  1564587.670 ± 38483.142  ops/s
MyBenchmark.multiDispatch1K     1000  thrpt    5     3159.365 ±    36.310  ops/s
MyBenchmark.taskChaining        1000  thrpt    5  1372956.090 ± 67058.903  ops/s
```

Except being able to do more operations error margins are sufficiently lower with MpscCompoundQueue. I think this is currently a good trade-off replacement. Can you please maybe shed some light on intended use of CompoundQueue if I misunderstood it.

**Comment by nitsanw** [comment]
@xedin The compound queue will reduce contention by switching queues on a CAS fail. I think in a topology aware usecase you'd want an MPSC per NUMA node, since the cross node CAS contention may prove costly. JCTools at the moment has no topology awareness so this is not helpful.
I would try implementing a NodeLocal<T> variable and use it for doing a variant of MpscOnSpsc where node local MPSC are used to replace the thread local SPSC.
Numa locality is an often overlooked aspect in Java concurrency and maybe somewhere you can really break some exciting new grounds with Windmill.

**Comment by xedin** [comment]
@nitsanw Sounds good, I've filed #56 to make it happen!
